"use client"

import { useState, useEffect } from "react"
import { motion } from "framer-motion"
import { Download, FileText, Clock, AlertCircle, CheckCircle, RefreshCw, AlertTriangle } from "lucide-react"
import { useNavigate } from "react-router-dom"
import { getThreatLevelColor } from "../libs/scanUtils"

const Report = () => {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const navigate = useNavigate()

  // Example report for when no scan has been made
  const exampleReport = {
    fileName: "example-file.zip",
    fileSize: "1.24 MB",
    fileHash: "b8c3c8f5e56453e0f4e2dc4eb8ef8b60e72acb354bbf6504c61d927a6a15cd67",
    scannedAt: "2024-12-18 14:32:45",
    isMalicious: false,
    scanStatus: "Safe",
    threatLevel: "Low",
    details: {
      description: "The file appears safe and does not contain any known threats.",
      recommendation: "You can safely proceed with this file.",
    },
  }

  useEffect(() => {
    // Check if there's a report in localStorage
    const storedReport = localStorage.getItem("scanReport")
    const reportId = localStorage.getItem("reportId")

    if (storedReport) {
      try {
        setReport(JSON.parse(storedReport))
      } catch (error) {
        console.error("Error parsing stored report:", error)
      }
    } else if (reportId) {
      // If we have a reportId but no report, try to fetch it
      setLoading(true)
      setTimeout(() => {
        setLoading(false)
        setError("Report not found. It may have expired or been removed.")
      }, 1500)
    }
  }, [])

  const handleDownloadReport = () => {
    const reportData = report || exampleReport
    const reportText = `
TROJAN TRAP SCAN REPORT
=======================

SCAN SUMMARY
-----------
File Name: ${reportData.fileName}
File Size: ${reportData.fileSize}
SHA-256 Hash: ${reportData.fileHash}
Scan Date: ${new Date(reportData.scannedAt).toLocaleString()}
Threat Status: ${reportData.isMalicious ? "MALICIOUS" : reportData.scanStatus === "suspicious" ? "SUSPICIOUS" : "SAFE"}
Threat Level: ${reportData.threatLevel || "N/A"}

ANALYSIS DETAILS
--------------
${reportData.details.description}

RECOMMENDATION
------------
${reportData.details.recommendation}

${
  reportData.threats && reportData.threats.length > 0
    ? `
DETECTED THREATS
---------------
${reportData.threats.map((threat) => `- ${threat.name} (${threat.category}, ${threat.severity} severity)`).join("\n")}
`
    : ""
}

ADDITIONAL INFORMATION
--------------------
This report was generated by Trojan Trap on ${new Date().toLocaleString()}.
For more information, visit https://trojan-trap-seven.vercel.app/
  `

    const blob = new Blob([reportText], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `trojan-trap-report-${new Date().toISOString().slice(0, 10)}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleScanNewFile = () => {
    navigate("/scanner")
  }

  // Render threat categories as a bar chart
  const renderThreatCategories = (categories) => {
    if (!categories) return null

    const items = [
      { name: "Virus", value: categories.virus, color: "bg-red-500" },
      { name: "Spyware", value: categories.spyware, color: "bg-purple-500" },
      { name: "Trojan", value: categories.trojan, color: "bg-yellow-500" },
      { name: "Ransomware", value: categories.ransomware, color: "bg-blue-500" },
      { name: "Adware", value: categories.adware, color: "bg-green-500" },
    ].filter((item) => item.value > 0)

    return (
      <div className="mt-4 space-y-3">
        <h4 className="font-medium text-gray-700">Threat Analysis:</h4>
        {items.map((item, index) => (
          <div key={index} className="space-y-1">
            <div className="flex justify-between text-sm">
              <span>{item.name}</span>
              <span>{item.value}%</span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-2.5">
              <div className={`${item.color} h-2.5 rounded-full`} style={{ width: `${item.value}%` }}></div>
            </div>
          </div>
        ))}
      </div>
    )
  }

  const reportData = report || exampleReport

  return (
    <div className="max-w-4xl mx-auto p-6 flex flex-col items-center">
      <motion.h1
        className="text-3xl font-bold mb-12 text-center"
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        {report ? "Your Scan Report" : "Scan Report Example"}
      </motion.h1>

      {loading ? (
        <div className="flex flex-col items-center">
          <div className="w-12 h-12 border-4 border-green-500 border-t-transparent rounded-full animate-spin mb-4"></div>
          <p>Loading report...</p>
        </div>
      ) : error ? (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded w-full max-w-2xl">
          <p className="font-medium">Error</p>
          <p className="text-sm">{error}</p>
        </div>
      ) : (
        <motion.div
          className="w-full max-w-2xl bg-white rounded-lg border-2 border-gray-200 p-8 shadow-lg"
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-bold">Scan Details</h2>
            <div
              className={`px-3 py-1 rounded-full text-white text-sm font-medium ${
                reportData.isMalicious
                  ? "bg-red-500"
                  : reportData.scanStatus === "suspicious"
                    ? "bg-yellow-500"
                    : "bg-green-500"
              }`}
            >
              {reportData.isMalicious ? "Malicious" : reportData.scanStatus === "suspicious" ? "Suspicious" : "Safe"}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
            <div className="bg-gray-50 p-4 rounded-lg">
              <div className="flex items-center mb-3">
                <FileText className="w-5 h-5 mr-2 text-green-500" />
                <span className="font-bold text-gray-700">File Information</span>
              </div>
              <div className="space-y-2 pl-7">
                <div>
                  <span className="text-gray-600">Name:</span>
                  <span className="ml-2 font-medium">{reportData.fileName}</span>
                </div>
                <div>
                  <span className="text-gray-600">Size:</span>
                  <span className="ml-2 font-medium">{reportData.fileSize}</span>
                </div>
                <div>
                  <span className="text-gray-600">Type:</span>
                  <span className="ml-2 font-medium">{reportData.fileName.split(".").pop().toUpperCase()}</span>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg">
              <div className="flex items-center mb-3">
                <Clock className="w-5 h-5 mr-2 text-green-500" />
                <span className="font-bold text-gray-700">Scan Information</span>
              </div>
              <div className="space-y-2 pl-7">
                <div>
                  <span className="text-gray-600">Date:</span>
                  <span className="ml-2 font-medium">{new Date(reportData.scannedAt).toLocaleString()}</span>
                </div>
                <div>
                  <span className="text-gray-600">Status:</span>
                  <span
                    className={`ml-2 font-medium ${
                      reportData.isMalicious
                        ? "text-red-600"
                        : reportData.scanStatus === "suspicious"
                          ? "text-yellow-600"
                          : "text-green-600"
                    }`}
                  >
                    {reportData.isMalicious
                      ? "Malicious"
                      : reportData.scanStatus === "suspicious"
                        ? "Suspicious"
                        : "Safe"}
                  </span>
                </div>
                <div>
                  <span className="text-gray-600">Threat Level:</span>
                  <span className={`ml-2 font-medium ${getThreatLevelColor(reportData.threatLevel)}`}>
                    {reportData.threatLevel || "Low"}
                  </span>
                </div>
              </div>
            </div>
          </div>

          <div className="mb-6">
            <div className="font-bold text-gray-700 mb-2">SHA-256 Hash:</div>
            <div className="bg-gray-100 p-3 rounded font-mono text-sm break-all border border-gray-200">
              {reportData.fileHash}
            </div>
          </div>

          {/* Threat categories visualization */}
          {reportData.detectionCategories && renderThreatCategories(reportData.detectionCategories)}

          {/* Specific threats */}
          {reportData.threats && reportData.threats.length > 0 && (
            <div className="mt-4 mb-4">
              <h4 className="font-medium text-gray-700 mb-2">Detected Threats:</h4>
              <div className="space-y-2">
                {reportData.threats.map((threat, index) => (
                  <div key={index} className="bg-gray-50 p-3 rounded-md border border-gray-200">
                    <div className="flex justify-between">
                      <span className="font-medium">{threat.name}</span>
                      <span
                        className={`text-sm px-2 py-0.5 rounded-full ${
                          threat.severity === "critical"
                            ? "bg-red-100 text-red-800"
                            : threat.severity === "high"
                              ? "bg-orange-100 text-orange-800"
                              : "bg-yellow-100 text-yellow-800"
                        }`}
                      >
                        {threat.severity.charAt(0).toUpperCase() + threat.severity.slice(1)}
                      </span>
                    </div>
                    <div className="text-sm text-gray-600 mt-1">Category: {threat.category}</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="border-t pt-6 mt-6">
            <h3 className="font-bold text-xl mb-4 text-gray-800">Analysis Result</h3>
            <div
              className={`flex items-start p-5 rounded-md ${
                reportData.isMalicious
                  ? "bg-red-50 border border-red-100"
                  : reportData.scanStatus === "suspicious"
                    ? "bg-yellow-50 border border-yellow-100"
                    : "bg-green-50 border border-green-100"
              }`}
            >
              {reportData.isMalicious ? (
                <AlertCircle className="w-6 h-6 mr-4 text-red-500 flex-shrink-0 mt-1" />
              ) : reportData.scanStatus === "suspicious" ? (
                <AlertTriangle className="w-6 h-6 mr-4 text-yellow-500 flex-shrink-0 mt-1" />
              ) : (
                <CheckCircle className="w-6 h-6 mr-4 text-green-500 flex-shrink-0 mt-1" />
              )}
              <div>
                <p className="font-medium text-gray-800 mb-2">{reportData.details.description}</p>
                <p className="text-gray-600">{reportData.details.recommendation}</p>
              </div>
            </div>
          </div>

          <div className="mt-8 flex justify-center space-x-4">
            <button
              onClick={handleDownloadReport}
              className="bg-green-500 hover:bg-green-600 text-white py-3 px-6 rounded-md flex items-center shadow-md hover:shadow-lg transition-all duration-300 transform hover:scale-105"
            >
              <Download className="w-5 h-5 mr-2" />
              Download Report
            </button>

            <button
              onClick={handleScanNewFile}
              className="bg-blue-500 hover:bg-blue-600 text-white py-3 px-6 rounded-md flex items-center shadow-md hover:shadow-lg transition-all duration-300 transform hover:scale-105"
            >
              <RefreshCw className="w-5 h-5 mr-2" />
              Scan New File
            </button>
          </div>
        </motion.div>
      )}
    </div>
  )
}

export default Report
